server:
  port: 5051

spring:
  application:
    name: ms-process-manager
  profiles:
    active: dev

feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    de.yagub.deliverysystem: DEBUG