server:
  port: 5051

user:
  service:
    url: http://localhost:5050/api/users
    connect-timeout: 4000ms
    read-timeout: 8000ms

order:
  service:
    url: http://localhost:5052/api/orders
    connect-timeout: 4000ms
    read-timeout: 8000ms

wallet:
  service:
    url: http://localhost:5053/api/wallets
    connect-timeout: 4000ms
    read-timeout: 8000ms

spring:
  application:
    name: ms-process-manager

feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    de.yagub.deliverysystem: DEBUG