server:
  port: 5051

user:
  service:
    url: http://localhost:5050/api/users
    connect-timeout: 2000ms
    read-timeout: 5000ms

order:
  service:
    url: http://localhost:5052/api/orders
    connect-timeout: 2000ms
    read-timeout: 5000ms

spring:
  application:
    name: ms-process-manager
  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          user-service-register:
            failureRateThreshold: 50
            waitDurationInOpenState: 5000ms
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            registerHealthIndicator: true
          user-service-login:
            failureRateThreshold: 40
            waitDurationInOpenState: 3000ms
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            registerHealthIndicator: true
          order-service-create-order:
            failureRateThreshold: 40
            waitDurationInOpenState: 3000ms
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            registerHealthIndicator: true
          order-service-get-order-by-id:
            failureRateThreshold: 40
            waitDurationInOpenState: 3000ms
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            registerHealthIndicator: true
          order-service-get-orders-by-customer-id:
            failureRateThreshold: 40
            waitDurationInOpenState: 3000ms
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            registerHealthIndicator: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: circuitBreakers # Note the exact capitalization
    circuitbreakers:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
    resilience4j:
      enabled: true

resilience4j:
  circuitbreaker:
    register-health-indicator: true # Global registration

logging:
  level:
    root: WARN
    org.springframework.web: ERROR
    org.springframework.cloud.openfeign: ERROR
    de.yagub.deliverysystem.msprocessmanager: TRACE
    de.yagub.deliverysystem.msprocessmanager.controller: TRACE
    de.yagub.deliverysystem.msprocessmanager.config: TRACE
  file:
    name: logs/ms-process-manager.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"